### ISSUE TITLE
data/enums

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#13]
# Enums (Data)
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Enums.

Rama fuente: `data/enums`

**Comment by Vizten18** [comment]
Implementado las nuevas correcciones en redaccion y tambien implementado el uso del BaseEnum, hay algunas cositas que iré puliendo y tambien de hacer la nueva pagina que sea especificamente hablando del BaseEnum
