### ISSUE TITLE
domain/validators

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#15]
# Validadores
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Validadores.

Rama fuente: `domain/validators`

**Comment by SebCorrea** [comment]
Se documentó el apartado de superclase FormField, nombrado de los validadores, nombrado de clases para el manejo de errores de validacion, extension de FormField y extensión de FieldValidationFailure.
