### ISSUE TITLE
domain/entities

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#3]
# Entidades
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Entidades.

Rama fuente: `domain/entities`

**Comment by nathva** [comment]
@Vizten18 Acabo de hacer un commit con un primer borrador para la Sección "Clases" del capítulo de Entidades. Esto incluye: 

- Nombrado de entidades. 
- Extensión de la clase Equatable. 
- Documentación de la entidad.

**Comment by nathva** [comment]
Acabo de hacer un nuevo commit corrigiendo detalles de la Sección "Clases", específicamente con respecto al nombrado de entidades. 

Agregué instrucciones adicionales y corregí uno de los ejemplos para que se adecúe más a estas instrucciones.

**Comment by nathva** [comment]
Hice 3 PRs con las secciones que faltaban en el capítulo, siendo estas: Constructores, Métodos y Atributos. Todas fueron revisadas ya.
