### ISSUE TITLE
domain/usecases

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#7]
# Casos de Uso
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Casos de Uso.

Rama fuente: `domain/usecases`

**Comment by nathva** [comment]
@Vizten18 Helloo! Deje dos PRs hacia la rama domain/usecases con las secciones "Clases" y "Constructor" de Use Cases.

**Comment by nathva** [comment]
@Vizten18 Hello again! Ya corregí el comentario que me dejaste en el pr de clases

**Comment by nathva** [comment]
@Vizten18 Te hice un PR con la parte final de la documentación de casos de uso. Está toda la sección de métodos.
