### ISSUE TITLE
presentation/blocs

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#8]
# Blocs
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Blocs.

Rama fuente: `presentation/blocs`

**Comment by ortegadn** [comment]
@andrespd99 Hice un commit con la introducción a Bloc y con el inicio de nombrado de clases.

**Comment by ortegadn** [comment]
@andrespd99 una duda, en la sección de Blocs habíamos agregado una parte de extensión de clases donde se mencionaría el tema de los blocs de la librería comun de Avila. Específicamente que era lo que se espera explicar en esa sección? como funciona cada bloc? o como se usan?
