### ISSUE TITLE
presentation/features

### ISSUE THREAD

**Issue by andrespd99** [Avila-Tek/avilatek-mobile-docs#9]
# Features
Usar este Issue como medio de comunicación de las propuestas sobre la documentación de Features.

Rama fuente: `presentation/features`

**Comment by CADSV** [comment]
Ya subí la sección de la creación de un feature. Me avisas qué tal cuando puedas @nathva

**Comment by nathva** [comment]
@CADSV Helloo! Revisado el pr de Feature creation, te deje unos comentarios.
